### ISSUE TITLE
PackageScore fields can be null

### ISSUE THREAD

**Issue by Rexios80** [leoafarias/pub_api_client#10]
If a package was recently updated, some of the information in PackageScore can be null. For example: grantedPubPoints and popularityScore. These should be handled by the client.

**Comment by leoafarias** [comment]
@Rexios80 In this particular case I believe the correct behavior would be just to have those params nullable. The other option is to set a default value, but not sure if that would be the correct apporoach.

**Comment by Rexios80** [comment]
Nullable fields makes the most sense to me

**Comment by leoafarias** [comment]
@Rexios80 would you like to do a PR for this? If not I will try to get to it over the weekend

**Comment by Rexios80** [comment]
I will if I have time. I'm going to have to do some testing to figure out what fields are nullable unless you happen to already know.

**Comment by Rexios80** [comment]
#11
