### ISSUE TITLE
How to authenticate the user for likes

### ISSUE THREAD

**Issue by ZiyadF296** [leoafarias/pub_api_client#14]
Hey,
First and foremost, thank you for this awesome package.

So I have a very simple application where users can like pub packages. However as mentioned in the documentation, I will need to authenticate the user. Could you perhaps elaborate on how to authenticate?

Thank you.

**Comment by leoafarias** [comment]
@ZiyadF296 There is no way to authenticate a user that I am aware of, however, you can pass existing credentials to the client. The credentials normally are stored on your local machine, this was done for local tools.

**Comment by ZiyadF296** [comment]
Ok thank you,
However I have another question and rather than opening another issue, I will just mention it here.

Is there a way where I can get if the publisher is verified or not? I know I can get the `publisherId` but am not sure about how to get if that publisher is verified.

**Comment by leoafarias** [comment]
@ZiyadF296 sorry but I am not aware of an endpoint that would return that information
