### ISSUE TITLE
Is it possible to get the documentation of a specific package in markdown?

### ISSUE THREAD

**Issue by ZiyadF296** [leoafarias/pub_api_client#15]
Hey,

So I have been trying out the package lately. I know I can get whether or not the package has documentation, but can I get the actual documentation as markdown or just string?

Thank you.

**Comment by leoafarias** [comment]
There are no endpoints that I am aware of that would do this. I believe the best way is to get the package repository and get the readme. It might be a bit tough if its a monorepo, but you can probably do a look-up matching the package name in that case.
