### ISSUE TITLE
feature request: expand fetchFlutterFavorites

### ISSUE THREAD

**Issue by polilluminato** [leoafarias/pub_api_client#22]
Hi everyone, for one of my side projects I'm using this package to create a desktop app to browse [pub.dev](https://pub.dev/) using the same concept of the AppStore, Windows Store, or other stores on Linux distros.

In my case I need to create a section with the list of packages of the Flutter Favorite program and those associated with Google that can be retrieved respectively with this two APIs:

- `fetchGooglePackages`
- `fetchFlutterFavorites`

Unfortunately, these two functions only return the `List <String>` with the package names while in my case I would need the complete information about the package represented by the `PubPackage` object. Right now I solved this issue by calling the `fetchFlutterFavorites` and after that in another widget call the `packageInfo` API to get all the info, something like that using [Riverpod](https://riverpod.dev/):

```dart

final allFlutterFavoritesProvider = FutureProvider.autoDispose<List<String>>((ref) async {
  return await PubClient().fetchFlutterFavorites();
});

final singlePackageProvider = FutureProvider.autoDispose.family<PubPackage, String>((ref, packageName) async {
  return await PubClient().packageInfo(packageName);
});

[...]

Widget build(BuildContext context, WidgetRef ref) {
    AsyncValue<List<String>> allFlutterFavoritesList = ref.watch(allFlutterFavoritesProvider);

    return Column(
      children: [
        ...
        allFlutterFavoritesList.when(
          loading: ...
          error: ...
          data: (list) {
            return GridView.builder(
              shrinkWrap: true,
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 3,
                  crossAxisSpacing: kDefaultPagePadding,
                  mainAxisSpacing: kDefaultPagePadding),
              itemCount: list.length,
              itemBuilder: (_, int index) {
                return PackageGridBox(
                  packageName: list.elementAt(index),
                );
              },
            );
          },
        ),
      ],
    );
  }

[...]

class PackageGridBox extends ConsumerWidget {
  const PackageGridBox({Key? key, required this.packageName}) : super(key: key);

  final String packageName;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    AsyncValue<PubPackage> singlePackage = ref.watch(singlePackageProvider(packageName));

    return singlePackage.when(
      loading: ...
      error: ...
      data: (package) {
        return Container(
          decoration: kDefaultBoxDecoration(context),
          child: Text(package.toString()),
        );
      },
    );
  }
}

```

Do you think it might be useful to add an API that allows you to immediately have all the information about the packages and not just the package name? Something like that:

```dart
/// Retrieves all the flutter favorites PubPackage
Future<List<PubPackage>> fetchFlutterFavoritesPubPackage() async {
  final searchResults = await search('is:flutter-favorite');
  final results = await recursivePaging(this, searchResults);
  return await Future.wait(
    results.map((r) => packageInfo(r.package)).toList());
}
```
I know that for all the packages you must wait for all the `packageInfo` calls but it might be useful to someone.

Best regards,
Alberto

**Comment by leoafarias** [comment]
@polilluminato this is an ongoing challenge with the API. I had to do something similar for the flutter.space API. 

https://github.com/fluttertools/flutter.space/blob/main/lib/helpers.dart#L114

I think a helper function might be interesting, let me know if the link provided is something that it would work.

**Comment by polilluminato** [comment]
@leoafarias you recommend using [flutter-favorites.json](https://api.flutter.space/v1/pub/flutter-favorites.json) to get information on Flutter Favorites Packages to show in a list and then use the `pub_api_client` package to get more information on a detail page? 

In this way, I don't have to change the behavior of the `pub_api_client` package. 
I can use both the [flutter.space](https://github.com/fluttertools/flutter.space) endpoints to get lists (favorite, google, popular, most liked, and so on) and `pub_api_client` package to get detailed information.

Sounds good to me 😀

**Comment by leoafarias** [comment]
Yes feel free to use whatever you need for Flutter Spaces, if you end up with flutter space SDK, feel free to do a PR!

**Comment by Rexios80** [comment]
@polilluminato Can't you just use the search method?

**Comment by leoafarias** [comment]
@Rexios80 I think @polilluminato wants to also get the information within the search, as search returns just the package names. Not sure if this has changed in the last few months

**Comment by polilluminato** [comment]
You are right @leoafarias but right now I'm not developing that side project anymore, so nothing has changed since my last message. 

@Rexios80 the search methods returns only the package name, so, to display a "pretty" list and not just the name, I have to call another API as mentioned by @leoafarias
