### ISSUE TITLE
feature request: add support for Cloudsmith

### ISSUE THREAD

**Issue by m-skolnick** [leoafarias/pub_api_client#33]
I'm curious how much of a lift you feel it would be (or whether it's even possible) to expand this package to be able to interact with a third party hosting service such as Cloudsmith. 

They must have a similar API set up at least for fetching package info and the `latest version` etc. 

My guess is it's probably a better idea to create a separate client, but it would be really cool if we had something like a `packages_info` that supported querying for pub.dev packages as well as hosted packages.

My Use Case:
1. We have an internal CLI tool written in Dart and published on Cloudsmith. I would like to add an "auto-update" feature where it checks every few hours if the package has a new version.
2. I would like to add PR checks to my packages published on cloudsmith to make sure they are not about to publish a package version that is already published to Cloudsmith.

Any thoughts would be appreciated!

**Comment by leoafarias** [comment]
I think ideally, a new client is created, or a proxy API is created for Cloudsmith that is compatible with Pub.dev
