### ISSUE TITLE
Add repository and issue_tracker to pubspec data

### ISSUE THREAD

**Issue by jxstxn1** [leoafarias/pub_api_client#46]
If we make the following GET request: `https://pub.dev/api/packages/go_router/versions/13.2.0` which is reflected in the Package as `packageVersionInfo` we receive in the `pubspec` section `repository` and issue_tracker.

It would be great if we could add them as nullable strings to this package

**Comment by leoafarias** [comment]
@jxstxn1 We will most likely need to send a PR to the `pubspec` package here: https://pub.dev/packages/pubspec.

**Comment by jxstxn1** [comment]
Yeah, I realized this too. The package seems quite unmaintained, but I found a possible alternative.
The `pubspec_parser` package which is containing a fully functional pubspec class seems up-to-date and is maintained by `dart-lang`. 
I opened an Issue there in the hope that they extract the Feature Complete Pubspec and publish it.
In the meantime we could think about copying and pasting this pubspec to increase the feature completeness

What are your thoughts @leoafarias?

**Comment by leoafarias** [comment]
I agree. The issue with pubspec_parser is that last I checked, they don't have a toJson or toMap method, and it doesn't seem as straight forward to add.

**Comment by jxstxn1** [comment]
What do you think about extracting just the Pubspec class and add toJson/toMap Methods on our own?

**Comment by leoafarias** [comment]
Didn't want to reinvent the wheel here, but it's a bit absurd the solution is not straight forward.z so I understand..

What do you think about passing the raw "yaml" in case the model does not contain the information?

**Comment by jxstxn1** [comment]
This could also be an Option which would prevent reinventing the real.

**Comment by leoafarias** [comment]
@jxstxn1 While looking at this, it seems that the `Pubspec` already contains a property called `unparsedYaml`. Can you check if this works for you? I will leave this open to investigate it better in the future.

**Comment by jxstxn1** [comment]
Hey @leoafarias
I checked the `unparsedYaml` and it works fine. It's worth noticing that it doesn't contain the whole unparsed YAML, but instead only the values the package can't handle.

**Comment by leoafarias** [comment]
@jxstxn1 in that case maybe we can use  Extension methods to add the missing fields. What do you think?

**Comment by jxstxn1** [comment]
I think that would be a great idea
Shall I draft a test version so that we can discuss the implementation details in a PR?

**Comment by jxstxn1** [comment]
@leoafarias PR is opened!
Let me know if I should change something :)
