### ISSUE TITLE
error: MapperException: Failed to decode (PubPackage).versions(List<PackageVersion>?).item(PackageVersion).pubspec(PubSpec): type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by csells** [leoafarias/pub_api_client#51]
this happens for the sqlite3 package.

**Comment by leoafarias** [comment]
I think I might have to make everything nullable..

**Comment by csells** [comment]
Actually I think you want to make the fewest things null as possible. I pulled data for the top 500 packages and this was the only issue I found.

**Comment by leoafarias** [comment]
@csells There is one thing that I have noticed: when a package is being analyzed, sometimes the API can return nullable values as well. I will take a look at this.

**Comment by leoafarias** [comment]
@csells This has been fixed in version 3.0.0. I have bumped it as a major version because there are some small breaking changes when moving from the `pubspec` to the `pubspec_parse` package.

**Comment by csells** [comment]
thank you!
